### ISSUE TITLE
Error when visiting /api/cart

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs-streaming-product-page#2]
```shell
Potentially unhandled rejection [4] {"UNSENT":0,"OPENED":1,"HEADERS_RECEIVED":2,"LOADING":3,"DONE":4,"readyState":4,"responseText":"Error: unable to verify the first certificate\n    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:188:7)\n    at TLSSocket._finishInit (_tls_wrap.js:610:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)","responseXML":"","status":0,"statusText":{"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},"withCredentials":true,"__url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"?","query":"","pathname":"/api/cart","path":"/api/cart?","href":"/api/cart?"}} (WARNING: non-Error used)
Potentially unhandled rejection [9] Error
    at ClientRequest.<anonymous> (/Users/matthew/dev/done-ssr/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by matthewp** [comment]
Curling `/api/cart` doesn't produce these errors, so it must be something the browser i adding (cookies probably).

**Comment by matthewp** [comment]
This was fixed in done-ssr.
