### ISSUE TITLE
Page crashes when using incremental renderer

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs-streaming-product-page#3]
😩

```shell
Potentially unhandled rejection [27] Error
    at ClientRequest.<anonymous> (/Users/matthew/dev/done-ssr/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at PriorityNode.removeChild (/Users/matthew/dev/donejs-streaming-product-page/node_modules/spdy-transport/lib/spdy-transport/priority.js:74:3)
    at PriorityNode.remove (/Users/matthew/dev/donejs-streaming-product-page/node_modules/spdy-transport/lib/spdy-transport/priority.js:62:15)
    at PriorityTree.add (/Users/matthew/dev/donejs-streaming-product-page/node_modules/spdy-transport/lib/spdy-transport/priority.js:163:23)
    at Stream._initPriority (/Users/matthew/dev/donejs-streaming-product-page/node_modules/spdy-transport/lib/spdy-transport/stream.js:101:25)
    at new Stream (/Users/matthew/dev/donejs-streaming-product-page/node_modules/spdy-transport/lib/spdy-transport/stream.js:76:8)
    at Connection._createStream (/Users/matthew/dev/donejs-streaming-product-page/node_modules/spdy-transport/lib/spdy-transport/connection.js:388:16)
    at Connection._handleHeaders (/Users/matthew/dev/donejs-streaming-product-page/node_modules/spdy-transport/lib/spdy-transport/connection.js:436:21)
    at Connection._handleFrame (/Users/matthew/dev/donejs-streaming-product-page/node_modules/spdy-transport/lib/spdy-transport/connection.js:319:10)
    at Parser.<anonymous> (/Users/matthew/dev/donejs-streaming-product-page/node_modules/spdy-transport/lib/spdy-transport/connection.js:156:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
```

**Comment by matthewp** [comment]
This is a bug in `spdy`. Going to reduce down and submit a test there (maybe a fix).

**Comment by matthewp** [comment]
Bug: https://github.com/spdy-http2/node-spdy/issues/318

**Comment by matthewp** [comment]
Fixed the bug, switching to donejs-spdy until the PR is accepted.
